language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

before_script:
  - echo $NAME
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
  - cargo install-update -a

script:
  - cd til && mdbook build && mdbook test